#!/bin/bash
trap "exit" INT
jack_wait -w
gst-launch-1.0 jackaudiosrc name="GstreamerJack" connect=0 ! audio/x-raw, channels=1 ! audioconvert ! audioresample ! opusenc ! rtpopuspay pt=111 ! udpsink host=192.168.86.31 port=5002
