#!/bin/bash

function clean_up {

    # Perform program exit housekeeping
    kill $MPLAYER_PID
    exit
}

trap clean_up SIGHUP SIGINT SIGTERM
#trap "exit 130" INT
while true
do
#jackd -r -ddummy -r44100 -p512 &
jackd -R -d alsa -P hw:CODEC -C hw:CODEC,0 -r44100 -p512 -n 2 &
MPLAYER_PID=$!
wait $MPLAYER_PID
sleep 1
done